// BAKR PRO - Partners Account Page
// Full version: manual/automatic income, custom percentages, saved settlements, PDF save/share.

import React, { useEffect, useMemo, useState } from 'react';
import { Plus, Save, Trash2, Users, RefreshCw, Truck, Wallet, TrendingUp, TrendingDown, FileText, Share2, FolderOpen, X, Pencil } from 'lucide-react';
import { AppLayout } from '@/components/layout/AppLayout';
import { fetchEquipment, type Equipment } from '@/lib/equipment';
import jsPDF from 'jspdf';
import { Filesystem, Directory } from '@capacitor/filesystem';
import { Share } from '@capacitor/share';

type IncomeMode = 'auto' | 'manual';
type Partner = { id:string; name:string; percentage:number; paid:number; notes:string };
type DayRow = { day:number; tripPrice?:number; expenseAmount?:number };
type ExternalExpenseRecord = { date?:string; equipmentId?:string; amount?:number };
type SavedSettlement = {
 id:string; createdAt:string; updatedAt?:string; equipmentId:string; equipmentName:string; year:number; month:number;
 incomeMode:IncomeMode; manualIncome:number; monthlyIncome:number; monthlyManualExpenses:number; linkedExpenses:number;
 additionalExpenses:number; totalExpenses:number; distributable:number; partners:Partner[];
};

const STORAGE_KEY='bakr_pro_partner_settlements_v3';
const OLD_STORAGE_KEY='bakr_pro_partner_settlements_v2';
const EXTERNAL_EXPENSE_KEY='crane_accounting_driver_equipment_expenses_v1';
const monthNames=['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];
const n=(v:any)=>Number.isFinite(Number(v))?Number(v):0;
const money=(v:number)=>`${n(v).toLocaleString('en-US',{maximumFractionDigits:2})} ر.س`;
const makePartner=():Partner=>({id:`${Date.now()}-${Math.random()}`,name:'',percentage:0,paid:0,notes:''});
const safeFileName=(v:string)=>v.replace(/[\\/:*?"<>|]/g,'-').replace(/\s+/g,'-');
function getDateParts(v:string){const p=String(v||'').split('-');if(p.length<3)return null;const year=n(p[0]),month=n(p[1]),day=n(p[2]);return year&&month&&day?{year,month,day}:null}

export function PartnersPage(){
 const now=new Date();
 const [equipmentList,setEquipmentList]=useState<Equipment[]>([]); const [equipmentId,setEquipmentId]=useState(''); const [equipmentLoading,setEquipmentLoading]=useState(true);
 const [year,setYear]=useState(now.getFullYear()); const [month,setMonth]=useState(now.getMonth());
 const [incomeMode,setIncomeMode]=useState<IncomeMode>('auto'); const [manualIncome,setManualIncome]=useState(0);
 const [monthlyIncome,setMonthlyIncome]=useState(0); const [monthlyManualExpenses,setMonthlyManualExpenses]=useState(0); const [linkedExpenses,setLinkedExpenses]=useState(0); const [additionalExpenses,setAdditionalExpenses]=useState(0);
 const [partners,setPartners]=useState<Partner[]>([makePartner(),makePartner(),makePartner()]);
 const [loadingAccount,setLoadingAccount]=useState(false); const [savedSettlements,setSavedSettlements]=useState<SavedSettlement[]>([]); const [historyOpen,setHistoryOpen]=useState(false); const [editingId,setEditingId]=useState<string|null>(null); const [savingPdf,setSavingPdf]=useState(false);

 useEffect(()=>{let cancelled=false;(async()=>{try{setEquipmentLoading(true);const result=await fetchEquipment();if(cancelled)return;const list=Array.isArray(result)?result:[];setEquipmentList(list);if(list.length)setEquipmentId(String(list[0].id));}catch(e){console.error(e)}finally{if(!cancelled)setEquipmentLoading(false)}})();return()=>{cancelled=true}},[]);
 const selectedEquipment=useMemo(()=>equipmentList.find(i=>String(i.id)===String(equipmentId))||null,[equipmentList,equipmentId]); const equipmentName=selectedEquipment?.name||'';

 function loadSavedSettlements(){try{const raw=localStorage.getItem(STORAGE_KEY)||localStorage.getItem(OLD_STORAGE_KEY);const p=raw?JSON.parse(raw):[];setSavedSettlements(Array.isArray(p)?p.map((x:any)=>({...x,incomeMode:x.incomeMode==='manual'?'manual':'auto',manualIncome:n(x.manualIncome)})):[])}catch{setSavedSettlements([])}}
 useEffect(()=>loadSavedSettlements(),[]);

 function loadMonthlyAccount(){if(!equipmentId){setMonthlyIncome(0);setMonthlyManualExpenses(0);setLinkedExpenses(0);return}try{setLoadingAccount(true);const raw=localStorage.getItem(`monthly-ledger-v3-${equipmentId}-${year}-${month}`);let rows:DayRow[]=[];if(raw){const p=JSON.parse(raw);if(Array.isArray(p))rows=p}setMonthlyIncome(rows.reduce((s,r)=>s+n(r.tripPrice),0));setMonthlyManualExpenses(rows.reduce((s,r)=>s+n(r.expenseAmount),0));let ext:ExternalExpenseRecord[]=[];const er=localStorage.getItem(EXTERNAL_EXPENSE_KEY);if(er){const p=JSON.parse(er);if(Array.isArray(p))ext=p}setLinkedExpenses(ext.reduce((s,e)=>{if(String(e.equipmentId||'')!==String(equipmentId))return s;const d=getDateParts(e.date||'');return d&&d.year===year&&d.month===month+1?s+n(e.amount):s},0));}catch(e){console.error(e);setMonthlyIncome(0);setMonthlyManualExpenses(0);setLinkedExpenses(0)}finally{setLoadingAccount(false)}}
 useEffect(()=>loadMonthlyAccount(),[equipmentId,year,month]);

 const effectiveIncome=incomeMode==='manual'?manualIncome:monthlyIncome; const totalExpenses=monthlyManualExpenses+linkedExpenses+additionalExpenses; const distributable=effectiveIncome-totalExpenses;
 const percentageTotal=useMemo(()=>partners.reduce((s,p)=>s+n(p.percentage),0),[partners]); const distributed=useMemo(()=>partners.reduce((s,p)=>s+distributable*(n(p.percentage)/100),0),[partners,distributable]); const difference=distributable-distributed;
 function updatePartner(id:string,field:keyof Omit<Partner,'id'>,value:string){setPartners(old=>old.map(p=>p.id===id?{...p,[field]:field==='percentage'||field==='paid'?n(value):value}:p))}
 function distributeEqually(){if(!partners.length)return;const base=Number((100/partners.length).toFixed(4));let used=0;setPartners(partners.map((p,i)=>{const percentage=i===partners.length-1?Number((100-used).toFixed(4)):base;used+=percentage;return{...p,percentage}}))}
 function validateAccount(){if(!equipmentId){alert('اختر المعدة أو الكرين');return false}if(!partners.length){alert('أضف شريكاً واحداً على الأقل');return false}if(partners.some(p=>!p.name.trim())){alert('أدخل أسماء جميع الشركاء');return false}if(Math.abs(percentageTotal-100)>.01){alert(`مجموع نسب الشركاء يجب أن يكون 100%.\nالمجموع الحالي: ${percentageTotal.toFixed(2)}%`);return false}return true}
 function createRecord():SavedSettlement{return{id:editingId||String(Date.now()),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),equipmentId,equipmentName,year,month,incomeMode,manualIncome,monthlyIncome,monthlyManualExpenses,linkedExpenses,additionalExpenses,totalExpenses,distributable,partners:partners.map(p=>({...p}))}}
 function saveSettlement(){if(!validateAccount())return;const record=createRecord();let list=[...savedSettlements];const idx=list.findIndex(x=>x.id===record.id);if(idx>=0)list[idx]={...record,createdAt:list[idx].createdAt};else list=[record,...list];localStorage.setItem(STORAGE_KEY,JSON.stringify(list));setSavedSettlements(list);setEditingId(record.id);alert('تم حفظ حساب الشركاء بنجاح')}
 function openSettlement(i:SavedSettlement){setEditingId(i.id);setEquipmentId(String(i.equipmentId));setYear(i.year);setMonth(i.month);setIncomeMode(i.incomeMode==='manual'?'manual':'auto');setManualIncome(n(i.manualIncome));setMonthlyIncome(n(i.monthlyIncome));setMonthlyManualExpenses(n(i.monthlyManualExpenses));setLinkedExpenses(n(i.linkedExpenses));setAdditionalExpenses(n(i.additionalExpenses));setPartners(i.partners?.map(p=>({...p,id:p.id||`${Date.now()}-${Math.random()}`}))||[]);setHistoryOpen(false);window.scrollTo({top:0,behavior:'smooth'})}
 function deleteSettlement(id:string){if(!confirm('هل تريد حذف حساب الشركاء المحفوظ؟'))return;const next=savedSettlements.filter(x=>x.id!==id);localStorage.setItem(STORAGE_KEY,JSON.stringify(next));setSavedSettlements(next);if(editingId===id)setEditingId(null)}
 function newSettlement(){setEditingId(null);setIncomeMode('auto');setManualIncome(0);setAdditionalExpenses(0);setPartners([makePartner(),makePartner(),makePartner()]);loadMonthlyAccount()}

 function buildPdf(){if(!validateAccount())return null;const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'});const w=doc.internal.pageSize.getWidth();doc.setFillColor(8,21,38);doc.rect(0,0,w,40,'F');doc.setTextColor(245,158,11);doc.setFontSize(21);doc.text('BAKR PRO',w/2,14,{align:'center'});doc.setTextColor(255,255,255);doc.setFontSize(13);doc.text('PARTNERS ACCOUNT',w/2,24,{align:'center'});doc.setFontSize(9);doc.text(`${equipmentName||'Equipment'} - ${month+1}/${year}`,w/2,32,{align:'center'});let y=50;const summary:[string,number][]=[['Income',effectiveIncome],['Monthly Expenses',monthlyManualExpenses],['Driver / Equipment Expenses',linkedExpenses],['Additional Expenses',additionalExpenses],['Total Expenses',totalExpenses],['Net Distribution',distributable]];doc.setFontSize(10);summary.forEach(([l,v])=>{doc.setFillColor(245,247,250);doc.roundedRect(15,y,180,10,2,2,'F');doc.setTextColor(30,41,59);doc.text(l,20,y+6.5);doc.text(`${n(v).toLocaleString('en-US',{maximumFractionDigits:2})} SAR`,190,y+6.5,{align:'right'});y+=12});y+=5;doc.setFillColor(15,95,183);doc.rect(15,y,180,10,'F');doc.setTextColor(255,255,255);doc.text('PARTNERS DISTRIBUTION',w/2,y+6.5,{align:'center'});y+=13;partners.forEach((p,index)=>{const due=distributable*n(p.percentage)/100,rem=due-n(p.paid);doc.setTextColor(30,41,59);doc.text(`Partner ${index+1} | ${p.percentage}% | Due ${due.toFixed(2)} | Paid ${n(p.paid).toFixed(2)} | Remaining ${rem.toFixed(2)}`,18,y+7);y+=11});return doc}
 async function savePdf(){const doc=buildPdf();if(!doc)return;try{setSavingPdf(true);const fileName=safeFileName(`BAKR-PRO-Partners-${equipmentName||'Equipment'}-${month+1}-${year}.pdf`);const base64=doc.output('datauristring').split(',')[1];await Filesystem.writeFile({path:`BAKR_PRO/${fileName}`,data:base64,directory:Directory.Documents,recursive:true});alert('تم حفظ ملف PDF بنجاح في المستندات')}catch(e){console.error(e);doc.save(`BAKR-PRO-Partners-${month+1}-${year}.pdf`)}finally{setSavingPdf(false)}}
 async function sharePdf(){const doc=buildPdf();if(!doc)return;try{setSavingPdf(true);const fileName=safeFileName(`BAKR-PRO-Partners-${equipmentName||'Equipment'}-${month+1}-${year}.pdf`);const base64=doc.output('datauristring').split(',')[1];const result=await Filesystem.writeFile({path:fileName,data:base64,directory:Directory.Cache});await Share.share({title:'حساب الشركاء - BAKR PRO',text:`حساب الشركاء - ${equipmentName} - ${monthNames[month]} ${year}`,url:result.uri,dialogTitle:'مشاركة حساب الشركاء'})}catch(e){console.error(e);alert('تعذر مشاركة ملف PDF')}finally{setSavingPdf(false)}}

 const inputStyle:React.CSSProperties={width:'100%',boxSizing:'border-box',padding:12,borderRadius:12,border:'1px solid #263b58',background:'#081526',color:'#fff',outline:'none',fontSize:13};
 const cardStyle:React.CSSProperties={background:'linear-gradient(145deg,#0d1b2f,#07111f)',border:'1px solid rgba(255,255,255,.08)',borderRadius:20,padding:14};
 const btn:React.CSSProperties={padding:13,borderRadius:13,border:'1px solid rgba(96,165,250,.25)',background:'rgba(59,130,246,.08)',color:'#93c5fd',fontWeight:800};

 return <AppLayout><div dir="rtl" style={{padding:16,paddingBottom:120,color:'#fff'}}>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><h1 style={{margin:0,fontSize:26}}>حساب الشركاء</h1><p style={{color:'#94a3b8',fontSize:11}}>توزيع صافي حساب الكرين على الشركاء</p></div><Users size={28} color="#60a5fa"/></div>
  <button style={{...btn,width:'100%',marginTop:12}} onClick={()=>{loadSavedSettlements();setHistoryOpen(true)}}><FolderOpen size={17}/> الحسابات المحفوظة ({savedSettlements.length})</button>
  <section style={{...cardStyle,marginTop:12}}><div><Truck size={17} color="#fbbf24"/> <b>المعدة / الكرين</b></div><select value={equipmentId} onChange={e=>setEquipmentId(e.target.value)} disabled={equipmentLoading} style={{...inputStyle,marginTop:8}}>{!equipmentList.length&&<option value="">لا توجد معدات</option>}{equipmentList.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:8}}><select value={month} onChange={e=>setMonth(n(e.target.value))} style={inputStyle}>{monthNames.map((x,i)=><option key={x} value={i}>{x}</option>)}</select><input type="number" value={year} onChange={e=>setYear(n(e.target.value))} style={inputStyle}/></div></section>
  <section style={{...cardStyle,marginTop:12}}><b>مصدر الدخل</b><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:8}}><button style={btn} onClick={()=>setIncomeMode('auto')}>تلقائي</button><button style={btn} onClick={()=>setIncomeMode('manual')}>مبلغ يدوي</button></div>{incomeMode==='auto'?<><div style={{textAlign:'center',marginTop:10,color:'#4ade80',fontWeight:900,fontSize:20}}>{money(monthlyIncome)}</div><button style={{...btn,width:'100%',marginTop:8}} onClick={loadMonthlyAccount}><RefreshCw size={16}/> {loadingAccount?'جاري...':'تحديث الآن'}</button></>:<input type="number" inputMode="decimal" value={manualIncome||''} onChange={e=>setManualIncome(n(e.target.value))} placeholder="اكتب مبلغ الدخل" style={{...inputStyle,marginTop:10,fontSize:17}}/>}</section>
  <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:12}}><Summary label="إجمالي الدخل" value={money(effectiveIncome)} color="#4ade80" icon={<TrendingUp size={17}/>}/><Summary label="مصاريف الحساب الشهري" value={money(monthlyManualExpenses)} color="#fb7185" icon={<TrendingDown size={17}/>}/><Summary label="مصاريف السواقين والمعدات" value={money(linkedExpenses)} color="#fb923c"/><Summary label="إجمالي المصاريف" value={money(totalExpenses)} color="#f87171"/></div>
  <section style={{...cardStyle,marginTop:12}}><label style={{fontSize:11,color:'#94a3b8'}}>مصاريف إضافية خاصة بالشراكة</label><input type="number" value={additionalExpenses||''} onChange={e=>setAdditionalExpenses(n(e.target.value))} style={{...inputStyle,marginTop:7}}/></section>
  <section style={{...cardStyle,marginTop:12,textAlign:'center'}}><Wallet size={25} color="#60a5fa"/><div style={{fontSize:11,color:'#94a3b8'}}>صافي المبلغ القابل للتوزيع</div><div style={{fontSize:25,fontWeight:900,color:distributable>=0?'#4ade80':'#fb7185'}}>{money(distributable)}</div></section>
  <section style={{...cardStyle,marginTop:12}}><div style={{display:'flex',justifyContent:'space-between'}}><div><b>الشركاء</b><div style={{fontSize:11,color:'#fbbf24'}}>مجموع النسب: {percentageTotal.toFixed(2)}%</div></div><button style={btn} onClick={distributeEqually}>توزيع متساوي</button></div>{partners.map((p,index)=>{const due=distributable*p.percentage/100,remaining=due-p.paid;return <div key={p.id} style={{padding:10,border:'1px solid rgba(255,255,255,.08)',borderRadius:14,marginTop:10}}><div style={{display:'flex',justifyContent:'space-between'}}><b>الشريك {index+1}</b>{partners.length>1&&<button onClick={()=>setPartners(old=>old.filter(x=>x.id!==p.id))} style={{background:'transparent',border:0,color:'#fb7185'}}><Trash2 size={17}/></button>}</div><input placeholder="اسم الشريك" value={p.name} onChange={e=>updatePartner(p.id,'name',e.target.value)} style={{...inputStyle,marginTop:8}}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:8}}><input type="number" placeholder="النسبة %" value={p.percentage||''} onChange={e=>updatePartner(p.id,'percentage',e.target.value)} style={inputStyle}/><input type="number" placeholder="السحوبات / المدفوع" value={p.paid||''} onChange={e=>updatePartner(p.id,'paid',e.target.value)} style={inputStyle}/></div><input placeholder="ملاحظات" value={p.notes} onChange={e=>updatePartner(p.id,'notes',e.target.value)} style={{...inputStyle,marginTop:8}}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:8}}><Summary label="المستحق" value={money(due)} color="#4ade80" small/><Summary label="المتبقي" value={money(remaining)} color="#fbbf24" small/></div></div>})}<button style={{...btn,width:'100%',marginTop:10}} onClick={()=>setPartners(old=>[...old,makePartner()])}><Plus size={17}/> إضافة شريك</button></section>
  <div style={{marginTop:12}}><Summary label="فارق التوزيع" value={money(difference)} color={Math.abs(difference)<.01?'#4ade80':'#fbbf24'}/></div>
  <div style={{display:'grid',gap:8,marginTop:12}}><button style={{...btn,background:'#0f5fb7',color:'#fff'}} onClick={saveSettlement}><Save size={18}/> {editingId?'حفظ التعديلات':'حفظ حساب الشركاء'}</button><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><button style={btn} disabled={savingPdf} onClick={savePdf}><FileText size={17}/> حفظ PDF</button><button style={btn} disabled={savingPdf} onClick={sharePdf}><Share2 size={17}/> مشاركة PDF</button></div><button style={btn} onClick={newSettlement}>+ حساب شراكة جديد</button></div>
  {historyOpen&&<div style={{position:'fixed',inset:0,zIndex:99999,background:'rgba(2,6,15,.96)',overflowY:'auto',padding:18}}><div style={{maxWidth:430,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between'}}><h2>الحسابات المحفوظة</h2><button style={btn} onClick={()=>setHistoryOpen(false)}><X size={18}/></button></div>{!savedSettlements.length?<p>لا توجد حسابات محفوظة</p>:savedSettlements.map(i=><div key={i.id} style={{...cardStyle,marginTop:8}}><b>{i.equipmentName||'كرين'} — {monthNames[i.month]} {i.year}</b><div style={{color:'#4ade80',marginTop:5}}>{money(i.distributable)}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:8}}><button style={btn} onClick={()=>openSettlement(i)}><Pencil size={15}/> فتح وتعديل</button><button style={{...btn,color:'#fb7185'}} onClick={()=>deleteSettlement(i.id)}><Trash2 size={15}/> حذف</button></div></div>)}</div></div>}
 </div></AppLayout>
}

function Summary({label,value,color,small=false,icon}:{label:string;value:string;color:string;small?:boolean;icon?:React.ReactNode}){return <div style={{background:'linear-gradient(145deg,#0d1b2f,#07111f)',border:'1px solid rgba(255,255,255,.07)',borderRadius:small?12:17,padding:small?9:12,textAlign:'center'}}>{icon&&<div style={{color,display:'flex',justifyContent:'center'}}>{icon}</div>}<div style={{color:'#94a3b8',fontSize:small?9:10}}>{label}</div><div style={{color,fontWeight:900,fontSize:small?12:15,marginTop:5}}>{value}</div></div>}
