import { useState, useEffect, useRef, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { Settings as SettingsIcon, Save, Download, Upload, Phone, MapPin, Building2, CreditCard, Image, SlidersHorizontal, Printer, Gauge, WifiOff, RotateCcw } from 'lucide-react';
import { AppLayout } from '@/components/layout/AppLayout'; import { PageHeader } from '@/components/layout/PageHeader'; import { Card } from '@/components/ui/Card'; import { CraneLogo } from '@/components/CraneLogo';
import { fetchSettings, saveSettings, DEFAULT_SETTINGS, type AppSettings } from '@/lib/settings'; import { supabase } from '@/lib/supabase'; import { paymentMethods } from '@/lib/transactions';

function Toggle({value,onChange,label,desc,icon:Icon}:{value:boolean;onChange:(v:boolean)=>void;label:string;desc:string;icon:any}){return <button type="button" onClick={()=>onChange(!value)} className="w-full flex items-center gap-3 text-right"><div className="w-10 h-10 rounded-xl bg-white/5 flex items-center justify-center"><Icon className="w-5 h-5 text-gold-400"/></div><div className="flex-1"><b className="text-sm text-white">{label}</b><p className="text-[11px] text-slate-500 mt-0.5">{desc}</p></div><div className={`w-12 h-7 rounded-full p-1 transition-colors ${value?'bg-gold-500':'bg-white/10'}`}><div className={`w-5 h-5 rounded-full bg-white transition-transform ${value?'-translate-x-5':'translate-x-0'}`}/></div></button>}
export function SettingsPage(){const nav=useNavigate(),fileRef=useRef<HTMLInputElement>(null);const [s,setS]=useState<AppSettings|null>(null),[saving,setSaving]=useState(false),[msg,setMsg]=useState('');const load=useCallback(()=>fetchSettings().then(setS),[]);useEffect(()=>{load()},[load]);
function logo(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f||!s)return;const r=new FileReader();r.onload=()=>setS({...s,logo:String(r.result)});r.readAsDataURL(f)}
async function save(){if(!s)return;setSaving(true);await saveSettings(s);setMsg('تم حفظ الإعدادات بنجاح');setSaving(false);setTimeout(()=>setMsg(''),1800)}
async function exp(){const tables=['equipment','customers','jobs','expenses','payments','invoices','monthly_equipment_days','settings','job_types'];const out:any={version:2,createdAt:new Date().toISOString()};for(const t of tables){const {data}=await supabase.from(t).select('*');out[t]=data??[]}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));a.download=`crane-backup-${new Date().toISOString().slice(0,10)}.json`;a.click()}
async function imp(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f||!confirm('استعادة النسخة الاحتياطية واستبدال البيانات الحالية؟'))return;const b=JSON.parse(await f.text());for(const [t,rows] of Object.entries(b)){if(Array.isArray(rows)&&!['version','createdAt'].includes(t)){await supabase.from(t).delete().neq('id','__none__');if(rows.length)await supabase.from(t).insert(rows)}}await load();setMsg('تمت استعادة النسخة')}
if(!s)return <AppLayout showHeader={false} showBottomNav={false}><PageHeader title="الإعدادات" icon={SettingsIcon} onBack={()=>nav('/')}/></AppLayout>;
const input='w-full bg-ink-850/80 border border-white/10 rounded-xl py-3 px-4 text-sm text-white outline-none focus:border-gold-500/40';return <AppLayout showHeader={false} showBottomNav={false}><div className="pt-4"><PageHeader title="الإعدادات" subtitle="خيارات حقيقية محفوظة على الجهاز" icon={SettingsIcon} onBack={()=>nav('/')}/>
<Card className="p-5 mb-4"><div className="flex items-center gap-4"><div className="w-20 h-20 rounded-3xl bg-ink-900 overflow-hidden flex items-center justify-center">{s.logo?<img src={s.logo} className="w-full h-full object-cover"/>:<CraneLogo size={56}/>}</div><div className="flex-1"><b className="text-white">صورة وواجهة التطبيق</b><p className="text-xs text-slate-500 mt-1">اختر شعارًا من صور الجوال</p><button onClick={()=>fileRef.current?.click()} className="mt-3 px-3 py-2 rounded-xl bg-gold-500/10 text-gold-400 text-xs flex items-center gap-2"><Image className="w-4 h-4"/> تغيير الصورة</button><input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={logo}/></div></div></Card>
<Card className="p-4 mb-4 space-y-3"><div className="flex items-center gap-2 text-gold-400 mb-2"><Building2 className="w-4 h-4"/><b className="text-sm">بيانات النشاط</b></div><input className={input} value={s.appName} onChange={e=>setS({...s,appName:e.target.value})} placeholder="اسم البرنامج"/><input className={input} value={s.businessName} onChange={e=>setS({...s,businessName:e.target.value})} placeholder="اسم النشاط"/><div className="grid grid-cols-2 gap-2"><div className="relative"><Phone className="absolute right-3 top-3.5 w-4 h-4 text-slate-500"/><input className={`${input} pr-10`} value={s.phone} onChange={e=>setS({...s,phone:e.target.value})}/></div><div className="relative"><MapPin className="absolute right-3 top-3.5 w-4 h-4 text-slate-500"/><input className={`${input} pr-10`} value={s.city} onChange={e=>setS({...s,city:e.target.value})}/></div></div><div className="grid grid-cols-2 gap-2"><div className="relative"><CreditCard className="absolute right-3 top-3.5 w-4 h-4 text-slate-500"/><input className={`${input} pr-10`} value={s.currency} onChange={e=>setS({...s,currency:e.target.value})}/></div><select className={input} value={s.defaultPaymentMethod} onChange={e=>setS({...s,defaultPaymentMethod:e.target.value})}>{paymentMethods.map(x=><option key={x}>{x}</option>)}</select></div><input className={input} value={s.reportTitle} onChange={e=>setS({...s,reportTitle:e.target.value})} placeholder="عنوان التقارير"/></Card>
<Card className="p-4 mb-4 space-y-5"><div className="flex items-center gap-2 text-gold-400"><SlidersHorizontal className="w-4 h-4"/><b className="text-sm">خيارات التشغيل</b></div><Toggle value={s.showOfflineBadge} onChange={v=>setS({...s,showOfflineBadge:v})} label="إظهار وضع بدون إنترنت" desc="شارة توضح أن البيانات محفوظة محليًا" icon={WifiOff}/><Toggle value={s.animations} onChange={v=>setS({...s,animations:v})} label="الحركات البصرية" desc="تشغيل أو تقليل مؤثرات الانتقال" icon={Gauge}/><Toggle value={s.compactMode} onChange={v=>setS({...s,compactMode:v})} label="الوضع المضغوط" desc="يعرض عناصر أكثر في الشاشة" icon={SlidersHorizontal}/><Toggle value={s.printPhone} onChange={v=>setS({...s,printPhone:v})} label="إظهار الجوال في الطباعة" desc="إضافة رقم الجوال في الفواتير والتقارير" icon={Printer}/></Card>
{msg&&<p className="text-sm text-income text-center mb-3">{msg}</p>}<button onClick={save} disabled={saving} className="w-full py-3.5 rounded-xl bg-gradient-to-br from-gold-400 to-gold-600 text-ink-950 font-bold flex items-center justify-center gap-2"><Save className="w-5 h-5"/>{saving?'جاري الحفظ...':'حفظ جميع الإعدادات'}</button>
<div className="grid grid-cols-2 gap-3 mt-4"><button onClick={exp} className="py-3 rounded-xl bg-white/5 border border-white/10 text-sm text-white flex items-center justify-center gap-2"><Download className="w-4 h-4"/>نسخة احتياطية</button><label className="py-3 rounded-xl bg-white/5 border border-white/10 text-sm text-white flex items-center justify-center gap-2"><Upload className="w-4 h-4"/>استعادة<input type="file" accept=".json" onChange={imp} className="hidden"/></label></div><button onClick={()=>setS({...DEFAULT_SETTINGS})} className="w-full mt-3 py-3 rounded-xl text-xs text-slate-400 flex items-center justify-center gap-2"><RotateCcw className="w-4 h-4"/> استعادة الإعدادات الافتراضية</button>
</div></AppLayout>}
